open_workshops:
  - id: 1
    title: Ruby1.9
    subtitle: Introdução
    info:
      - Instalação com RVM (Ruby Version Management);
      - Instalando e usando Git e o GitHub;
      - Discussão sobre tipagem forte e dinâmica;
      - Operadores, condicionais e iteradores;
      - Strings, Fixnums/Floats, booleanos, Arrays, Hashes, Regexps e Ranges;
      - Algum diferenças do Ruby 1.9 para o Ruby 1.8.7;
      - Usando blocos each, map/collect, select...;
    dates: 30/1, 1/2 e 3/2
    status: [success, "Inscrições abertas"]
    list_id: 218864
    
  - id: 2
    title: Ruby1.9
    subtitle: Orientação a Objetos
    info:
      - Classes e herança;
      - Diferença entre métodos de classe e métodos de instância;
      - Módulos;
      - Métodos públicos, privados e protegidos;
      - Monkeypatching;
      - Operadores como métodos;
      - Métodos que executam blocos;
    dates: 6, 8 e 10/2
    status: [success, "Inscrições abertas"]
    list_id: 218865
  
  - id: 3
    title: Rails3.1
    subtitle: MVC
    info:
      - Bundler;
      - Como funcionam os requests;
      - Como passar dados dos controles para as views;
      - O que é o layout?
      - Renderizando outras views;
      - Que bibliotecas existem para views?
      - Criando modelos e definindo itens e coleções nos controles;
      - O que é um recurso?
      - Criando rotas para recursos;
      - Criando um "Scaffold";
      - "Métodos básicos do AR: new, create, save, update_attributes, destroy, find, all..."
      - Validações no modelo;
      - "Escopos: where, order, limit, offset..."
      - Views parciais e renderização de coleções.
      - "Relacionamentos entre modelos: belongs_to, has_one, has_many..."
      - "Testando modelos e controles com Test::Unit;"
      - "Filtros nos controler: before, after e around."
    dates: 13, 15 e 16/2
    status: [success, "Inscrições abertas"]
    list_id: 218867
  
  - id: 4
    title: Rails3.1
    subtitle: Avançado
    info: 
      - Sass, coffee/javascript & assets pipeline;
      - Instalando gems;
      - Quais as gems mais usadas para cada coisa?
      - Autenticação com Devise;
      - Paginação com kaminari;
      - Controllers DRY com InheritedResources e HasScope;
      - Sessão, cookies e flashes;
      - Respondendo com JSON a chamadas Ajax;
      - Testando com Test::Unit;
      - Colocando aplicações no ar com Heroku;
    dates: 27/2, 29/2 e 2/3
    status: [success, "Inscrições abertas"]
    list_id: 218868

  - id: 5
    title: Rspec2
    subtitle: Testando aplicações Rails
    info:
      - Aguarde mais informações
    dates: 5, 7 e 9/3
    status: [success, "Inscrições abertas"]
    list_id: 218869 
  
  
  - id: 7
    title: Ruby1.9
    subtitle: Metaprogramação
    info: 
      - Entendendo DSLs (Domain specific languages);
      - Criando métodos dinamicamente;
      - Redefinindo e removendo métodos;
      - method_missing;
      - eval, class_eval e instance_eval;
      - Blocos e escopos;
      - Gems para metaprogramação;
    dates: 12, 14 e 16/3
    status: [success, "Inscrições abertas"]
    list_id: 218871 
  
  - id: 8
    title: Rails3.1
    subtitle: Deployment, infraestrutura & escalabilidade 
    info:
      - "<strong>Deployment</strong>"
      - Continuous integration;
      - Continuous deployment;
      - Development, staging e production environments;
      - Web servers (apache e nginx);
      - Ruby application servers (unicorn, thin, mongrel, passenger..);
      - "<strong>Infraestrutura</strong>"
      - Máquinas virtuais e servidores dedicados;
      - Hospedagem de assets;
      - Envio de emails;
      - Balanceamento de carga;
      - Autoscaling;
      - "<strong>Escalabilidade</strong>"
      - Identificando gargalos
      - Background jobs (rescue e delayed job) e queues;
      - Cache da aplicação (rails cache, memoise);
      - Ferramentas de cache (memcache, redis) 
      - Otimização de banco de dados;
    dates: 19, 21 e 23/3
    status: [success, "Inscrições abertas"]
    list_id: 218872

  - id: 9
    title: Aprendendo a programar
    subtitle: Parte 1
    info:
      - É designer e quer aprender programação? É MBA e quer saber do que seus programadores estão falando? A cadeira de lógica tá dificil? Quer acelerar seu aprendizado?
      - Neste workshop você <i>não irá aprender</i> lógica de programação. Você aprenderá <i>na prática</i> e de forma <i>divertida</i> como programar.
      - Usaremos jogos online e ferramentas inovadoras para quem está começando, ensinando como base a linguagem Ruby (viu, nada de Pascal*).
      - "* Mas não se preocupe, isso irá lhe ajudar com o Pascal."
    dates: 26, 28 e 30/3
    status: [success, "Inscrições abertas"]
    list_id: 225202
  
  - id: 10
    title: Aprendendo a programar
    subtitle: Parte 2
    info:
      - É designer e quer aprender programação? É MBA e quer saber do que seus programadores estão falando? A cadeira de lógica tá dificil? Quer acelerar seu aprendizado?
      - Neste workshop você <i>não irá aprender</i> lógica de programação. Você aprenderá <i>na prática</i> e de forma <i>divertida</i> como programar.
      - Usaremos jogos online e ferramentas inovadoras para quem está começando, ensinando como base a linguagem Ruby (viu, nada de Pascal*).
      - "* Mas não se preocupe, isso irá lhe ajudar com o Pascal."
    dates: 2, 4 e 6/4
    status: [success, "Inscrições abertas"]
    list_id: 225204

coming_workshops:
  - title: Rails3.1
    subtitle: Integração com redes sociais
    status: [notice, "Aguarde"]
    list_id: 221033

  - title: BackboneJS & Jasmine
    subtitle: JS de verdade para suas aplicações
    status: [notice, "Aguarde"]
    list_id: 218870
  
  - title: NodeJS1.6
    subtitle: WebSockets com Express Básico
    status: [notice, "Aguarde"]
    list_id: 218859

  - title: NodeJS1.6
    subtitle: WebSockets com Express Avançado
    status: [notice, "Aguarde"]
    list_id: 218860
  
  - title: JaxGL
    subtitle: WebGL para programadores Rails
    status: [notice, "Aguarde"]
    list_id: 218861

  - title: Vim
    subtitle: Subtitle here!
    status: [notice, "Aguarde"]
    list_id: 218862
