open_workshops:
  - id: 1
    title: Ruby1.9
    subtitle: Introdução
    info:
      - Instalação com RVM (Ruby Version Management);
      - Instalando e usando Git e o GitHub;
      - Discussão sobre tipagem forte e dinâmica;
      - Operadores, condicionais e iteradores;
      - Strings, Fixnums/Floats, booleanos, Arrays, Hashes, Regexps e Ranges;
      - Algum diferenças do Ruby 1.9 para o Ruby 1.8.7;
      - Usando blocos each, map/collect, select...;
    dates: 30/1, 1/2 e 3/2
    status: [success, "Inscrições abertas"]
    list_id: 218864
    
  - id: 2
    title: Ruby1.9
    subtitle: Orientação a Objetos
    info:
      - Classes e herança;
      - Diferença entre métodos de classe e métodos de instância;
      - Módulos;
      - Métodos públicos, privados e protegidos;
      - Monkeypatching;
      - Operadores como métodos;
      - Métodos que executam blocos;
    dates: 6, 8 e 10/2
    status: [success, "Inscrições abertas"]
    list_id: 218865
  
  - id: 3
    title: Rails3.1
    subtitle: MVC
    info:
      - Bundler;
      - Como funcionam os requests;
      - Como passar dados dos controles para as views;
      - O que é o layout?
      - Renderizando outras views;
      - Que bibliotecas existem para views?
      - Criando modelos e definindo itens e coleções nos controles;
      - O que é um recurso?
      - Criando rotas para recursos;
      - Criando um "Scaffold";
      - "Métodos básicos do AR: new, create, save, update_attributes, destroy, find, all..."
      - Validações no modelo;
      - "Escopos: where, order, limit, offset..."
      - Views parciais e renderização de coleções.
      - "Relacionamentos entre modelos: belongs_to, has_one, has_many..."
      - "Testando modelos e controles com Test::Unit;"
      - "Filtros nos controler: before, after e around."
    dates: 13, 15 e 16/2
    status: [success, "Inscrições abertas"]
    list_id: 218867
  
  - id: 4
    title: Rails3.1
    subtitle: Avançado
    info: 
      - Sass, coffee/javascript & assets pipeline;
      - Instalando gems;
      - Quais as gems mais usadas para cada coisa?
      - Autenticação com Devise;
      - Paginação com kaminari;
      - Controllers DRY com InheritedResources e HasScope;
      - Sessão, cookies e flashes;
      - Respondendo com JSON a chamadas Ajax;
      - Testando com Test::Unit;
      - Colocando aplicações no ar com Heroku;
    dates: 27/2, 29/2 e 2/3
    status: [success, "Inscrições abertas"]
    list_id: 218868

  - id: 5
    title: Rspec2
    subtitle: Testando aplicações Rails
    info:
      - Aguarde mais informações
    dates: 5, 7 e 9/3
    status: [success, "Inscrições abertas"]
    list_id: 218869 
  
  - id: 6
    title: BackboneJS & Jasmine
    subtitle: JS de verdade para suas aplicações
    info:
      - Aguarde mais informações
    dates: 12, 14 e 16/3
    status: [success, "Inscrições abertas"]
    list_id: 218870
  
  - id: 7
    title: Ruby1.9
    subtitle: Metaprogramação
    info: 
      - Entendendo DSLs (Domain specific languages);
      - Criando métodos dinamicamente;
      - Redefinindo e removendo métodos;
      - method_missing;
      - eval, class_eval e instance_eval;
      - Blocos e escopos;
      - Gems para metaprogramação;
    dates: 19, 21 e 23/3
    status: [success, "Inscrições abertas"]
    list_id: 218871 
  
  - id: 8
    title: Rails3.1
    subtitle: Deployment, escalabilidade & cloud computing
    info:
      - Aguarde mais informações
    dates: 26, 28 e 30/3
    status: [success, "Inscrições abertas"]
    list_id: 218872
  
coming_workshops:
  - title: Rails3.1
    subtitle: Integração com redes sociais
    dates: 2, 4 e 6/4
    status: [notice, "Aguarde"]
    list_id: 221033

  - title: NodeJS1.6
    subtitle: WebSockets com Express Básico
    dates: 2, 4 e 6/4
    status: [notice, "Aguarde"]
    list_id: 218859

  - title: NodeJS1.6
    subtitle: WebSockets com Express Avançado
    dates: 2, 4 e 6/4
    status: [notice, "Aguarde"]
    list_id: 218860
  
  - title: JaxGL
    subtitle: WebGL para programadores Rails
    dates: 9, 11 e 13/4
    status: [notice, "Aguarde"]
    list_id: 218861

  - title: Vim
    subtitle: Subtitle here!
    dates: 16, 18 e 20/4
    status: [notice, "Aguarde"]
    list_id: 218862
